import { HISTORY_FACTS } from './history-data.js';

/** Original, short practice questions; source links support the teaching facts. */
export const FACT_TOPICS = [
  { id: 'geography', name: 'Geography', description: 'Canadian and world capitals.' },
  { id: 'science', name: 'Science', description: 'Space, nature and how things work.' },
  { id: 'history', name: 'Canadian history', description: 'People, places and moments in Canada’s past.' },
];

const canadaSource = {
  title: 'Government of Canada: Canada’s regions',
  url: 'https://www.canada.ca/en/immigration-refugees-citizenship/corporate/publications-manuals/discover-canada/read-online/canadas-regions.html',
};
const countrySource = (name, code) => ({
  title: `United Nations: ${name} country profile`,
  url: `https://data.un.org/legacy/en/iso/${code}.html`,
});
const waterSource = {
  title: 'USGS Water Science School: Water’s changing states',
  url: 'https://www.usgs.gov/water-science-school/science/sublimation-and-water-cycle',
};

export const FACTS = [
  {
    id: 'geo-canada', topic: 'geography',
    question: 'What is the capital of Canada?', answer: 'Ottawa',
    choices: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'],
    hint: 'This capital’s name starts with O.',
    explanation: 'Ottawa is Canada’s national capital.',
    source: canadaSource,
  },
  {
    id: 'geo-ontario', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Ontario?', answer: 'Toronto',
    choices: ['Ottawa', 'Kingston', 'London', 'Toronto'],
    hint: 'Look for the city that begins with T.',
    explanation: 'Toronto is Ontario’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-quebec', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Quebec?', answer: 'Quebec City',
    choices: ['Quebec City', 'Montreal', 'Gatineau', 'Sherbrooke'],
    hint: 'The city and the province share a name.',
    explanation: 'Quebec City is the capital of the province of Quebec.',
    source: canadaSource,
  },
  {
    id: 'geo-british-columbia', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of British Columbia?', answer: 'Victoria',
    choices: ['Vancouver', 'Kelowna', 'Victoria', 'Whistler'],
    hint: 'The city’s name begins with “Vic”.',
    explanation: 'Victoria is British Columbia’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-nova-scotia', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Nova Scotia?', answer: 'Halifax',
    choices: ['Sydney', 'Halifax', 'Truro', 'Yarmouth'],
    hint: 'Look for the city that begins with H.',
    explanation: 'Halifax is Nova Scotia’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-alberta', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Alberta?', answer: 'Edmonton',
    choices: ['Calgary', 'Red Deer', 'Edmonton', 'Lethbridge'],
    hint: 'This capital’s name begins with “Ed”.',
    explanation: 'Edmonton is Alberta’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-saskatchewan', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Saskatchewan?', answer: 'Regina',
    choices: ['Saskatoon', 'Regina', 'Moose Jaw', 'Prince Albert'],
    hint: 'Look for a six-letter city beginning with R.',
    explanation: 'Regina is Saskatchewan’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-manitoba', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Manitoba?', answer: 'Winnipeg',
    choices: ['Brandon', 'Thompson', 'Steinbach', 'Winnipeg'],
    hint: 'This city’s name begins with “Win”.',
    explanation: 'Winnipeg is Manitoba’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-new-brunswick', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of New Brunswick?', answer: 'Fredericton',
    choices: ['Fredericton', 'Moncton', 'Saint John', 'Miramichi'],
    hint: 'Its name begins with “Fred” and ends with “ton”.',
    explanation: 'Fredericton is New Brunswick’s provincial capital.',
    source: canadaSource,
  },
  {
    id: 'geo-prince-edward-island', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Prince Edward Island?', answer: 'Charlottetown',
    choices: ['Summerside', 'Stratford', 'Charlottetown', 'Souris'],
    hint: 'The city’s name ends with the word “town”.',
    explanation: 'Charlottetown is the capital of Prince Edward Island, often called P.E.I.',
    source: canadaSource,
  },
  {
    id: 'geo-newfoundland-and-labrador', topic: 'geography', region: 'canada-provinces',
    question: 'What is the capital of Newfoundland and Labrador?', answer: 'St. John’s',
    choices: ['Corner Brook', 'St. John’s', 'Gander', 'Labrador City'],
    hint: 'The name begins with “St.”, short for Saint.',
    explanation: 'St. John’s is the capital of Newfoundland and Labrador.',
    source: canadaSource,
  },
  {
    id: 'geo-united-kingdom', topic: 'geography',
    question: 'What is the capital of the United Kingdom?', answer: 'London',
    choices: ['Manchester', 'Cardiff', 'Edinburgh', 'London'],
    hint: 'Its name starts with L and ends with n.',
    explanation: 'London is the capital of the United Kingdom.',
    source: countrySource('United Kingdom', 'gb'),
  },
  {
    id: 'geo-france', topic: 'geography',
    question: 'What is the capital of France?', answer: 'Paris',
    choices: ['Paris', 'Lyon', 'Nice', 'Marseille'],
    hint: 'This five-letter city begins with P.',
    explanation: 'Paris is France’s capital city.',
    source: countrySource('France', 'fr'),
  },
  {
    id: 'geo-japan', topic: 'geography',
    question: 'What is the capital of Japan?', answer: 'Tokyo',
    choices: ['Osaka', 'Kyoto', 'Tokyo', 'Nagoya'],
    hint: 'This five-letter city begins with T.',
    explanation: 'Tokyo is Japan’s capital city.',
    source: countrySource('Japan', 'jp'),
  },
  {
    id: 'geo-australia', topic: 'geography',
    question: 'What is the capital of Australia?', answer: 'Canberra',
    choices: ['Sydney', 'Canberra', 'Melbourne', 'Perth'],
    hint: 'Its name begins with “Can”, just like Canada.',
    explanation: 'Australia’s capital is Canberra.',
    source: countrySource('Australia', 'au'),
  },
  {
    id: 'geo-italy', topic: 'geography',
    question: 'What is the capital of Italy?', answer: 'Rome',
    choices: ['Venice', 'Milan', 'Naples', 'Rome'],
    hint: 'The four-letter answer begins with R.',
    explanation: 'Rome is Italy’s capital city.',
    source: countrySource('Italy', 'it'),
  },
  {
    id: 'geo-spain', topic: 'geography',
    question: 'What is the capital of Spain?', answer: 'Madrid',
    choices: ['Madrid', 'Barcelona', 'Seville', 'Valencia'],
    hint: 'Look for a six-letter city beginning with M.',
    explanation: 'Madrid is Spain’s capital city.',
    source: countrySource('Spain', 'es'),
  },
  {
    id: 'geo-egypt', topic: 'geography',
    question: 'What is the capital of Egypt?', answer: 'Cairo',
    choices: ['Alexandria', 'Luxor', 'Cairo', 'Aswan'],
    hint: 'Its name has five letters and begins with C.',
    explanation: 'Cairo is Egypt’s capital city.',
    source: countrySource('Egypt', 'eg'),
  },
  {
    id: 'geo-india', topic: 'geography',
    question: 'What is the capital of India?', answer: 'New Delhi',
    choices: ['Mumbai', 'New Delhi', 'Kolkata', 'Chennai'],
    hint: 'This capital’s name has two words.',
    explanation: 'New Delhi is India’s capital.',
    source: countrySource('India', 'in'),
  },
  {
    id: 'geo-brazil', topic: 'geography',
    question: 'What is the capital of Brazil?', answer: 'Brasilia',
    choices: ['Rio de Janeiro', 'São Paulo', 'Salvador', 'Brasilia'],
    hint: 'The country and its capital both begin with “Bra”.',
    explanation: 'Brasilia, spelled Brasília in Portuguese, is Brazil’s capital.',
    source: countrySource('Brazil', 'br'),
  },
  {
    id: 'geo-united-states', topic: 'geography',
    question: 'What is the capital of the United States?', answer: 'Washington, D.C.',
    choices: ['Washington, D.C.', 'New York City', 'Boston', 'Los Angeles'],
    hint: 'Look for a city name followed by two initials.',
    explanation: 'Washington, D.C., is the capital of the United States.',
    source: countrySource('United States', 'us'),
  },
  {
    id: 'sci-sun', topic: 'science',
    question: 'What kind of space object is the Sun?', answer: 'A star',
    choices: ['A planet', 'A moon', 'A star', 'A comet'],
    hint: 'It makes its own light and heat.',
    explanation: 'The Sun is the star nearest to Earth.',
    source: { title: 'NASA Space Place: All about the Sun', url: 'https://spaceplace.nasa.gov/all-about-the-sun/en/' },
  },
  {
    id: 'sci-mercury', topic: 'science',
    question: 'Which planet is closest to the Sun?', answer: 'Mercury',
    choices: ['Venus', 'Mercury', 'Earth', 'Mars'],
    hint: 'It is also the smallest of the eight planets.',
    explanation: 'Mercury is the first planet out from the Sun.',
    source: { title: 'NASA Space Place: All about Mercury', url: 'https://spaceplace.nasa.gov/all-about-mercury/en/' },
  },
  {
    id: 'sci-jupiter', topic: 'science',
    question: 'Which is the largest planet in our solar system?', answer: 'Jupiter',
    choices: ['Earth', 'Mars', 'Neptune', 'Jupiter'],
    hint: 'This giant planet has a storm called the Great Red Spot.',
    explanation: 'Jupiter is the biggest of the eight planets.',
    source: { title: 'NASA Space Place: All about Jupiter', url: 'https://spaceplace.nasa.gov/all-about-jupiter/en/' },
  },
  {
    id: 'sci-day-night', topic: 'science',
    question: 'What causes day and night on Earth?', answer: 'Earth spins',
    choices: ['Earth spins', 'The Sun switches off', 'Clouds cover the Sun', 'The Moon covers the Sun'],
    hint: 'Think about a globe turning in front of a lamp.',
    explanation: 'Earth’s rotation turns places toward the Sun and then away from it.',
    source: { title: 'NASA: What is Earth?', url: 'https://www.nasa.gov/learning-resources/for-kids-and-students/what-is-earth-grades-5-8/' },
  },
  {
    id: 'sci-ice', topic: 'science',
    question: 'Which state of matter is an ice cube?', answer: 'Solid',
    choices: ['Liquid', 'Gas', 'Solid', 'Plasma'],
    hint: 'Before it melts, it keeps its shape.',
    explanation: 'Ice is water in its solid state.',
    source: waterSource,
  },
  {
    id: 'sci-evaporation', topic: 'science',
    question: 'What is the change from liquid water to water vapour called?', answer: 'Evaporation',
    choices: ['Freezing', 'Evaporation', 'Melting', 'Condensation'],
    hint: 'Think about a puddle slowly drying after rain.',
    explanation: 'During evaporation, liquid water becomes a gas called water vapour.',
    source: { title: 'USGS Water Science School: Evaporation', url: 'https://www.usgs.gov/water-science-school/science/evaporation-and-water-cycle' },
  },
  {
    id: 'sci-freezing', topic: 'science',
    question: 'What change turns liquid water into ice?', answer: 'Freezing',
    choices: ['Boiling', 'Melting', 'Evaporation', 'Freezing'],
    hint: 'Think about cooling water in an ice-cube tray.',
    explanation: 'Freezing changes liquid water into solid ice.',
    source: waterSource,
  },
  {
    id: 'sci-roots', topic: 'science',
    question: 'Which plant parts take in water and hold the plant in the soil?', answer: 'Roots',
    choices: ['Roots', 'Flowers', 'Seeds', 'Petals'],
    hint: 'Think about the branching parts below the stem.',
    explanation: 'Roots absorb water and nutrients and help hold the plant in place.',
    source: { title: 'University of Illinois: Plant parts — roots', url: 'https://web.extension.illinois.edu/gpe/case1/c1facts2a.html' },
  },
  {
    id: 'sci-leaves', topic: 'science',
    question: 'Which parts of most green plants use light to make food?', answer: 'Leaves',
    choices: ['Roots', 'Seeds', 'Leaves', 'Petals'],
    hint: 'Look for the broad green parts that catch light.',
    explanation: 'Leaves make food using light, water and carbon dioxide. This is photosynthesis.',
    source: { title: 'University of Illinois: Plant parts — leaves', url: 'https://web.extension.illinois.edu/gpe/case1/c1facts2c.html' },
  },
  {
    id: 'sci-magnet-iron', topic: 'science',
    question: 'Which object will an ordinary magnet attract strongly?', answer: 'An iron nail',
    choices: ['A wooden stick', 'An iron nail', 'A plastic spoon', 'A rubber band'],
    hint: 'Choose the object made from a magnetic metal.',
    explanation: 'Iron is a magnetic material, so a magnet attracts an iron nail.',
    source: { title: 'NASA Space Math: Exploring magnetism', url: 'https://spacemath.gsfc.nasa.gov/SMBooks/MagMathV3.pdf' },
  },
  {
    id: 'sci-magnet-poles', topic: 'science',
    question: 'What happens when a north pole faces a south pole on two magnets?', answer: 'Attract each other',
    choices: ['Push apart', 'Lose their colour', 'Melt', 'Attract each other'],
    hint: 'These are different poles, rather than two matching poles.',
    explanation: 'Unlike poles attract. Two north poles or two south poles repel.',
    source: { title: 'U.S. Energy Information Administration: Magnets and electricity', url: 'https://www.eia.gov/energyexplained/electricity/magnets-and-electricity.php' },
  },
  {
    id: 'sci-hearing', topic: 'science',
    question: 'Which body parts collect sounds for hearing?', answer: 'Ears',
    choices: ['Ears', 'Eyes', 'Lungs', 'Teeth'],
    hint: 'Sound travels through a canal to a tiny vibrating drum.',
    explanation: 'Ears change sound vibrations into signals that travel to the brain.',
    source: { title: 'NIH: How do we hear?', url: 'https://www.nidcd.nih.gov/health/how-do-we-hear' },
  },
  {
    id: 'sci-heart', topic: 'science',
    question: 'Which organ pumps blood around your body?', answer: 'Heart',
    choices: ['Stomach', 'Brain', 'Heart', 'Liver'],
    hint: 'You can feel it beating in your chest.',
    explanation: 'The heart’s beats pump blood to the lungs and the rest of the body.',
    source: { title: 'NIH: How the heart beats', url: 'https://www.nhlbi.nih.gov/health/heart/heart-beats' },
  },
  {
    id: 'sci-habitat', topic: 'science',
    question: 'What is the natural place where a living thing lives called?', answer: 'A habitat',
    choices: ['An orbit', 'A habitat', 'An organ', 'A season'],
    hint: 'Think of a living thing’s home and the resources it needs.',
    explanation: 'A habitat provides the living space and resources an organism needs.',
    source: { title: 'National Park Service: Habitats of Shenandoah', url: 'https://www.nps.gov/common/uploads/teachers/lessonplans/Habitats%20Lesson%20Plan_5081.pdf' },
  },
  {
    id: 'sci-food-chain', topic: 'science',
    question: 'Which living thing makes its own food using sunlight?', answer: 'Grass',
    choices: ['A rabbit', 'A fox', 'A hawk', 'Grass'],
    hint: 'Look for a green plant rather than an animal.',
    explanation: 'Grass is a producer: it makes food using light and can feed animals.',
    source: { title: 'National Park Service: Food chains', url: 'https://www.nps.gov/teachers/classrooms/food-chain.htm' },
  },
  ...HISTORY_FACTS,
];
